export const CLIENT_COLLECTION_ID = 'clients';

export const FAVORITE_WORKER_COLLECTION_ID = 'favoriteWorkers';

export const WORKER_COLLECTION_ID = 'workers';

export const PORTFOLIO_COLLECTION_ID = 'portfolios';

export const WORK_COLLECTION_ID = 'works';

export const REVIEW_COLLECTION_ID = 'reviews';

export const SPECIALTY_COLLECTION_ID = 'specialties';

export const SPECIALTY_WORKER_COLLECTION_ID = 'specialtyWorkers';

export const RECRUIT_COLLECTION_ID = 'recruits';

export const PHONE_NUMBER_AUTH_COLLECTION_ID = 'phoneNumberAuth';

export const FIELDS = {
  NORMAL_WORKER: '보통인부',
  CARPENTER: '목수',
  FLOOR: '마루',
  LINOLEUM: '장판ㆍ데코',
  TILE: '타일',
  BATHROOM: '욕실ㆍ싱크대',
  WALLPAPER: '도배',
  FILM: '인테리어필름',
  METAL: '금속',
  WINDOW: '창호샤시',
  PAINT: '페인트ㆍ방수',
  PLASTERER: '미장',
  ELECTRICITY: '전기ㆍ소방',
  INSTALLATION: '설비',
  DEMOLITION: '철거',
};

export const HUGE_DISTRICTS = {
  SUDOGWON: '수도권',
  GANWON: '강원',
  CHUNGCHEONG: '충청',
  YEONGNAM: '영남',
  HONAM: '호남',
  JEJU: '제주',
};

export const LARGE_DISTRICTS = {
  SEOUL: '서울',
  GYEONGGI: '경기',
  INCHEON: '인천',
  GANGWON: '강원',
  CHUNGBUK: '충북',
  CHUNGNAM: '충남',
  DAEJEON: '대전',
  SEJONG: '세종',
  GYEONGBUK: '경북',
  GYEONGNAM: '경남',
  BUSAN: '부산',
  DAEGU: '대구',
  ULSAN: '울산',
  JEONBUK: '전북',
  JEONNAM: '전남',
  GWANGJU: '광주',
  JEJU: '제주',
};

// export const SEOUL_DISTRICTS = {
//   GANGNAM: '강남구',
//   GANGDONG: '강동구',
//   GANGBUK: '강북구',
//   GANGSEO: '강서구',
//   GWANAK: '관악구',
//   GWANGJIN: '광진구',
//   GURO: '구로구',
//   GEUMCHEON: '금천구',
//   NOWON: '노원구',
//   DOBONG: '도봉구',
//   DONGDAEMUN: '동대문구',
//   DONGJAK: '동작구',
//   MAPO: '마포구',
//   SEODAEMUN: '서대문구',
//   SEOCHO: '서초구',
//   SEONGDONG: '성동구',
//   SEONGBUK: '성북구',
//   SONGPA: '송파구',
//   YANGCHEON: '양천구',
//   YEONGDEUNGPO: '영등포구',
//   YONGSAN: '용산구',
//   EUNPYEONG: '은평구',
//   JONGNO: '종로구',
//   JUNG: '중구',
//   JUNGNANG: '중랑구',
// };

// export const INCHEON_DISTRICTS = {
//   JUNG: '중구',
//   DONG: '동구',
//   SEO: '서구',
//   MICHUHOL: '미추홀구',
//   YEONSU: '연수구',
//   NAMDONG: '남동구',
//   BUPYEONG: '부평구',
//   GYEYANG: '계양구',
//   GANGHWA: '강화군',
//   ONGJIN: '웅진군',
// };

export const DISTRICTS = {
  [LARGE_DISTRICTS.SEOUL]: [
    '강남구',
    '강동구',
    '강북구',
    '강서구',
    '관악구',
    '광진구',
    '구로구',
    '금천구',
    '노원구',
    '도봉구',
    '동대문구',
    '동작구',
    '마포구',
    '서대문구',
    '서초구',
    '성동구',
    '성북구',
    '송파구',
    '양천구',
    '영등포구',
    '용산구',
    '은평구',
    '종로구',
    '중구',
    '중랑구',
  ],
  [LARGE_DISTRICTS.GYEONGGI]: [
    '가평군',
    '고양시',
    '과천시',
    '광명시',
    '광주시',
    '구리시',
    '군포시',
    '김포시',
    '남양주시',
    '동두천시',
    '부천시',
    '성남시',
    '수원시',
    '시흥시',
    '안산시',
    '안성시',
    '안양시',
    '양주시',
    '양평군',
    '여주시',
    '연천군',
    '오산시',
    '용인시',
    '의왕시',
    '의정부시',
    '이천시',
    '파주시',
    '평택시',
    '포천시',
    '하남시',
    '화성시',
  ],
  [LARGE_DISTRICTS.INCHEON]: [
    '강화군',
    '계양구',
    '남동구',
    '동구',
    '미추홀구',
    '부평구',
    '서구',
    '연수구',
    '웅진군',
    '중구',
  ],
  [LARGE_DISTRICTS.GANGWON]: [
    '강릉시',
    '고성군',
    '동해시',
    '삼척시',
    '속초시',
    '양구군',
    '양양군',
    '영월군',
    '원주시',
    '인제군',
    '정선군',
    '철원군',
    '춘천시',
    '태백시',
    '평창군',
    '홍천군',
    '화천군',
    '횡성군',
  ],
  [LARGE_DISTRICTS.CHUNGBUK]: [
    '괴산군',
    '단양군',
    '보은군',
    '영동군',
    '옥천군',
    '음성군',
    '제천시',
    '증평군',
    '진천군',
    '청주시',
    '충주시',
  ],
  [LARGE_DISTRICTS.CHUNGNAM]: [
    '계룡시',
    '공주시',
    '금산군',
    '논산시',
    '당진시',
    '보령시',
    '부여군',
    '서산시',
    '서천군',
    '아산시',
    '예산군',
    '천안시',
    '청양군',
    '태안군',
    '홍성군',
  ],
  [LARGE_DISTRICTS.DAEJEON]: [
    '대덕구',
    '동구',
    '서구',
    '유성구',
    '중구',
  ],
  [LARGE_DISTRICTS.SEJONG]: [
    '세종',
  ],
  [LARGE_DISTRICTS.GYEONGBUK]: [
    '경산시',
    '경주시',
    '고령군',
    '구미시',
    '군위군',
    '김천시',
    '문경시',
    '봉화군',
    '상주시',
    '성주군',
    '안동시',
    '영덕군',
    '영양군',
    '영주시',
    '영천시',
    '예천군',
    '울릉군',
    '울진군',
    '의성군',
    '청도군',
    '청송군',
    '칠곡군',
    '포항시',
  ],
  [LARGE_DISTRICTS.GYEONGNAM]: [
    '거제시',
    '거창군',
    '고성군',
    '김해시',
    '남해군',
    '밀양시',
    '사천시',
    '산청군',
    '양산시',
    '의령군',
    '진주시',
    '창녕군',
    '창원시',
    '통영시',
    '하동군',
    '함안군',
    '함양군',
    '합천군',
  ],
  [LARGE_DISTRICTS.BUSAN]: [
    '강서구',
    '금정구',
    '기장구',
    '남구',
    '동구',
    '동래구',
    '부산진구',
    '북구',
    '사상구',
    '사하구',
    '서구',
    '수영구',
    '연제구',
    '영도구',
    '중구',
    '해운대구',
  ],
  [LARGE_DISTRICTS.DAEGU]: [
    '남구',
    '달서구',
    '달성구',
    '동구',
    '북구',
    '서구',
    '수성구',
    '중구',
  ],
  [LARGE_DISTRICTS.ULSAN]: [
    '남구',
    '동구',
    '북구',
    '울주군',
    '중구',
  ],
  [LARGE_DISTRICTS.JEONBUK]: [
    '고창군',
    '군산시',
    '김제시',
    '남원시',
    '무주군',
    '부안군',
    '순창군',
    '완주군',
    '익산시',
    '임실군',
    '장수군',
    '전주시',
    '정읍시',
    '진안군',
  ],
  [LARGE_DISTRICTS.JEONNAM]: [
    '강진군',
    '고흥군',
    '곡성군',
    '광양시',
    '구례군',
    '나주시',
    '담양군',
    '목포시',
    '무안군',
    '보성군',
    '순천시',
    '신안군',
    '여수시',
    '영광군',
    '영암군',
    '완도군',
    '장성군',
    '장흥군',
    '진도군',
    '함평군',
    '해남군',
    '화순군',
  ],
  [LARGE_DISTRICTS.GWANGJU]: [
    '광산구',
    '남구',
    '동구',
    '북구',
    '서구',
  ],
  [LARGE_DISTRICTS.JEJU]: [
    '서귀포시',
    '제주시',
  ],
};
